k3s_platform_kubeconfig_path: /etc/rancher/k3s/k3s.yaml

k3s_platform_external_secrets_chart_version: "0.20.4"
k3s_platform_reloader_chart_version: "1.3.0"
k3s_platform_caddy_chart_version: "1.3.0"
k3s_platform_apisix_chart_version: "2.13.0"
k3s_platform_external_dns_chart_version: "1.20.0"

k3s_platform_values:
  components:
    externalSecrets:
      enabled: true
    reloader:
      enabled: true
    caddy:
      enabled: true
      releaseName: caddy
      values:
        ingressController:
          enabled: true
        ingressClass:
          create: true
          name: caddy
          default: false
        service:
          type: LoadBalancer
    apisix:
      enabled: true
      releaseName: apisix
      values:
        etcd:
          enabled: false
        externalEtcd:
          user: ""
        ingress-controller:
          enabled: false
        dashboard:
          enabled: false
        gateway:
          enabled: true
          type: ClusterIP
        control:
          enabled: false
        apisix:
          admin:
            enabled: false
          deployment:
            mode: standalone
            role: data_plane
            standalone:
              config: |
                routes:
                  - id: 1
                    uri: "/*"
                    hosts:
                      - api.svc.plus
                    name: api-gateway-prod
                    upstream:
                      type: roundrobin
                      nodes:
                        "accounts.core-prod.svc.cluster.local:80": 1
                  - id: 2
                    uri: "/*"
                    hosts:
                      - api-pre.svc.plus
                    name: api-gateway-pre
                    upstream:
                      type: roundrobin
                      nodes:
                        "accounts.core-pre.svc.cluster.local:80": 1
    externalDns:
      enabled: true
      releaseName: external-dns
      values:
        provider: cloudflare
        policy: sync
        registry: txt
        txtOwnerId: svc-plus-k3s
        sources:
          - ingress
        domainFilters:
          - svc.plus
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token
                key: api-token
