---
xfce_user_home: "/home/{{ xfce_user }}"
xfce_xsession_file: "{{ xfce_user_home }}/.xsession"
xfce_xfconf_dir: "{{ xfce_user_home }}/.config/xfce4/xfconf/xfce-perchannel-xml"
xfce_xfwm4_config: "{{ xfce_xfconf_dir }}/xfwm4.xml"
xfce_chromium_desktop_dir: "{{ xfce_user_home }}/.local/share/applications"
xfce_xrdp_services:
  - xrdp-sesman
  - xrdp
