---
sealos_version: "5.0.0"
kubernetes_version: "v1.28.9"
pod_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"
kubeconfig_local_path: "./admin.conf"
cluster_name: "default"
masters: "{{ groups['masters'] | default([]) }}"
workers: "{{ groups['gpu_workers'] | default([]) }}"
ansible_ssh_user: "root"
