---
xfce_user: ubuntu

xfce_packages:
  - xfce4-session
  - xfce4-panel
  - xfce4-settings
  - xfdesktop4
  - xfce4-terminal
  - xfce4-power-manager
  - xfwm4
  - thunar
  - dbus-x11
  - xdg-utils
  - x11-xserver-utils
  - xserver-xorg-core
  - xorgxrdp
  - chromium
  - fonts-noto-cjk
  - xrdp

xfce_enable_ufw: true
xfce_rdp_port: 3389

xfce_disable_compositor: true
xfce_disable_animations: true
xfce_manage_chromium: true
xfce_chromium_wrapper_path: /usr/local/bin/chromium-xrdp
xfce_chromium_desktop_file: /home/{{ xfce_user }}/.local/share/applications/chromium-browser.desktop
xfce_chromium_base_dir: /home/{{ xfce_user }}/.local/share/chromium-xrdp
xfce_chromium_profile_dir: "{{ xfce_chromium_base_dir }}/profile"
xfce_chromium_common_dir: "{{ xfce_chromium_base_dir }}/common"
xfce_chromium_config_dir: "{{ xfce_chromium_base_dir }}/config"
xfce_chromium_data_dir: "{{ xfce_chromium_base_dir }}/data"

xfce_manage_user: true
xfce_user_shell: /bin/bash
xfce_user_groups:
  - sudo
xfce_user_password_plaintext: ""
