---
plasma_user: ubuntu

plasma_packages_debian:
  - plasma-desktop
  - kde-plasma-desktop
  - konsole
  - dolphin
  - dbus-x11
  - x11-xserver-utils
  - xserver-xorg-core
  - xorgxrdp
  - chromium
  - fonts-noto-cjk
  - xrdp

plasma_packages_fedora:
  - plasma-desktop
  - plasma-workspace
  - konsole
  - dolphin
  - dbus-x11
  - xorg-x11-server-Xorg
  - xorgxrdp
  - chromium
  - google-noto-sans-cjk-fonts
  - xrdp

plasma_packages_opensuse:
  - plasma-desktop
  - plasma5-session
  - konsole
  - dolphin
  - dbus-1-x11
  - xorg-x11-server
  - xorgxrdp
  - chromium
  - noto-sans-cjk-fonts
  - xrdp

plasma_enable_ufw: true
plasma_rdp_port: 3389

plasma_manage_user: true
plasma_user_shell: /bin/bash
plasma_user_groups:
  - sudo
plasma_user_password_plaintext: ""
