---
- name: Deploy ACP Gemini vhosts
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: roles/vhosts/xworkmate_bridge/
      vars:
        deploy_acp_codex: false
        deploy_acp_opencode: false
        deploy_acp_gemini: true
      tags: [xworkmate_bridge, acp_gemini]
