---
- name: Deploy ACP Gemini vhosts
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: roles/vhosts/deploy_acp_vhosts/
      vars:
        deploy_acp_codex: false
        deploy_acp_opencode: false
        deploy_acp_gemini: true
      tags: [deploy_acp_vhosts, acp_gemini]
