---
- name: Deploy ACP OpenCode vhosts
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: roles/vhosts/deploy_acp_vhosts/
      vars:
        deploy_acp_codex: false
        deploy_acp_opencode: true
        deploy_acp_gemini: false
      tags: [deploy_acp_vhosts, acp_opencode]
