---
- name: Deploy Modern IT History Docusaurus ebook
  hosts: "{{ modern_it_history_target_host | default('jp_xhttp_contabo_host') }}"
  gather_facts: true
  become: true
  roles:
    - roles/vhosts/nodejs
    - roles/vhosts/modern_it_history
