---
- name: Setup minimal XFCE + XRDP desktop
  hosts: jp-xhttp-contabo.svc.plus
  become: true
  gather_facts: true
  vars:
    xfce_manage_user: true
    xfce_user_password_plaintext: "L@xiaomin1250"
    xfce_user_shell: /bin/bash
    xfce_enable_ufw: false
  roles:
    - roles/vhosts/xfce_xrdp_minimal/
