---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when:
    - not ansible_check_mode

- name: Restart openclaw gateway
  ansible.builtin.command:
    cmd: "systemctl --user restart {{ gateway_openclaw_service_name }}.service"
  environment:
    HOME: "{{ gateway_openclaw_home }}"
    XDG_RUNTIME_DIR: "/run/user/{{ gateway_openclaw_service_uid }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ gateway_openclaw_service_uid }}/bus"
  become: true
  become_user: "{{ gateway_openclaw_service_user }}"
  when:
    - not ansible_check_mode

- name: Reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
  when:
    - not ansible_check_mode
