[masters]
k8s-master-01 ansible_host=10.0.0.10

[gpu_workers]
k8s-gpu-01 ansible_host=10.0.0.21 accelerator=nvidia-h100
k8s-gpu-02 ansible_host=10.0.0.22 accelerator=nvidia-h100

[ray_workers:children]
gpu_workers

[k8s_cluster:children]
masters
gpu_workers
