---
billing_service_source_dir: "{{ playbook_dir }}/../billing-service"
billing_service_app_dir: "/opt/billing-service"
billing_service_go_version: "1.25.1"
billing_service_go_root: "/usr/local/go"
billing_service_go_bin: "{{ billing_service_go_root }}/bin/go"
billing_service_binary_name: "billing-service"
billing_service_binary_path: "/usr/local/bin/{{ billing_service_binary_name }}"
billing_service_service_name: "billing-service"
billing_service_service_description: "billing-service service"
billing_service_user: "root"
billing_service_group: "root"
billing_service_env_dir: "/etc/default"
billing_service_env_path: "{{ billing_service_env_dir }}/billing-service"

billing_service_listen_addr: "127.0.0.1:8081"
billing_service_exporter_base_url: "http://127.0.0.1:8080"
billing_service_database_url: ""
billing_service_collect_interval: "1m"
billing_service_default_region: ""
billing_service_source_revision: "billing-service-v1"
billing_service_price_per_byte: "0"
billing_service_initial_included_quota_bytes: "0"
billing_service_initial_balance: "0"
