---
# Default deployment directory for Zitadel Docker stack
zitadel_deploy_dir: /opt/zitadel
zitadel_workspace: "{{ zitadel_deploy_dir }}"
zitadel_domain: auth.svc.plus
zitadel_masterkey: MasterkeyNeedsToHave32Characters
zitadel_api_bind_host: 127.0.0.1
zitadel_api_port: 19080
zitadel_login_bind_host: 127.0.0.1
zitadel_login_port: 19081
zitadel_caddyfile_path: /etc/caddy/Caddyfile
zitadel_caddy_conf_dir: /etc/caddy/conf.d
zitadel_caddy_fragment_path: /etc/caddy/conf.d/zitadel.caddy
