grafana_git_url: https://github.com/x-evor/gitops.git
grafana_root_dir: /srv/grafana/grafana-as-code
grafana_domain: grafana.svc.plus
metrics_domain: metrics.svc.plus
prom_url_for_grafana: "https://{{ metrics_domain }}/prom/"

# Plugin configuration
grafana_plugins_enable_alpha: true
grafana_plugins_app_tls_skip_verify_insecure: false
grafana_allow_loading_unsigned_plugins:
  - zinclabs_openobserve
grafana_admin_user: admin
grafana_admin_password: admin
