---
- name: Install minimal XFCE + XRDP stack
  ansible.builtin.import_tasks: install.yml
  tags: [xfce, xfce_install]

- name: Configure XFCE desktop user and XRDP session
  ansible.builtin.import_tasks: config.yml
  tags: [xfce, xfce_config]
