---
gnome_user: ubuntu

gnome_packages_debian:
  - gnome-session
  - gnome-shell
  - gnome-terminal
  - nautilus
  - dbus-x11
  - x11-xserver-utils
  - xserver-xorg-core
  - xorgxrdp
  - chromium
  - fonts-noto-cjk
  - xrdp

gnome_packages_fedora:
  - gnome-session
  - gnome-shell
  - gnome-terminal
  - nautilus
  - dbus-x11
  - xorg-x11-server-Xorg
  - xorgxrdp
  - chromium
  - google-noto-sans-cjk-fonts
  - xrdp

gnome_packages_opensuse:
  - gnome-session
  - gnome-shell
  - gnome-terminal
  - nautilus
  - dbus-1-x11
  - xorg-x11-server
  - xorgxrdp
  - chromium
  - noto-sans-cjk-fonts
  - xrdp

gnome_enable_ufw: true
gnome_rdp_port: 3389

gnome_manage_user: true
gnome_user_shell: /bin/bash
gnome_user_groups:
  - sudo
gnome_user_password_plaintext: ""
