---
- name: Set max_map_count for vLLM/Ray
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
    reload: yes

- name: Load ip_vs module
  modprobe:
    name: ip_vs
    state: present
