cloud_cli_prereqs_install_azure_cli: true
cloud_cli_prereqs_install_gcloud_cli: true
cloud_cli_prereqs_gcloud_version: 527.0.0
cloud_cli_prereqs_gcloud_install_root: /opt
cloud_cli_prereqs_gcloud_archive_map:
  x86_64: google-cloud-cli-linux-x86_64.tar.gz
  amd64: google-cloud-cli-linux-x86_64.tar.gz
  aarch64: google-cloud-cli-linux-arm.tar.gz
  arm64: google-cloud-cli-linux-arm.tar.gz

