---
# LiteLLM Admin UI Credentials
litellm_basic_auth_username: admin

# Database Configuration
litellm_database_host: "127.0.0.1"
litellm_database_port: "15432"
litellm_database_sslmode: "disable"
litellm_database_name: "litellm"
litellm_database_user: "litellm"