cloud_dev_desktop_windows_android_cmdline_tools_url: https://dl.google.com/android/repository/commandlinetools-win-13114758_latest.zip
cloud_dev_desktop_windows_android_sdk_api_level: "36"
cloud_dev_desktop_windows_android_build_tools_version: "36.0.0"
cloud_dev_desktop_windows_android_system_image: system-images;android-36;google_apis;x86_64
cloud_dev_desktop_windows_android_avd_name: cloud-dev-desktop-api36
cloud_dev_desktop_windows_android_optional_features:
  - Microsoft-Hyper-V-All
  - HypervisorPlatform
  - VirtualMachinePlatform
cloud_dev_desktop_windows_flutter_version: "3.41.5"
cloud_dev_desktop_windows_flutter_install_root: C:\tools\flutter
cloud_dev_desktop_windows_flutter_sdk_url: "https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_{{ cloud_dev_desktop_windows_flutter_version }}-stable.zip"
cloud_dev_desktop_windows_visualstudio_packages:
  - visualstudio2022buildtools
  - visualstudio2022-workload-vctools
  - visualstudio2022-workload-nativedesktop
