---
- name: Restart acp bridge server
  ansible.builtin.systemd:
    name: "{{ acp_bridge_server_service_name }}"
    state: restarted
    daemon_reload: true

- name: Reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
