---
- name: Reload bridge
  ansible.builtin.command: >-
    docker compose
    --project-name {{ xworkmate_bridge_project_name }}
    -f {{ xworkmate_bridge_compose_file }}
    restart bridge
  args:
    chdir: "{{ xworkmate_bridge_base_dir }}"
  when:
    - not ansible_check_mode
