---
- name: Include unified ACP vhost config tasks
  ansible.builtin.import_tasks: config.yml
  tags: [acp_vhosts, acp_vhosts_config]

- name: Include unified ACP vhost validation tasks
  ansible.builtin.import_tasks: validate.yml
  tags: [acp_vhosts, acp_vhosts_validate]
