group: master
namespace: vault
# When false, disables the Ingress for public access.
vault_public_access: false
update_secret: true
tls:
  - secret_name: vault-tls
    keyfile: /etc/ssl/svc.plus.key
    certfile: /etc/ssl/svc.plus.pem
