---
gpu_operator_namespace: "gpu-operator"
gpu_operator_release_name: "gpu-operator"
gpu_operator_chart_version: "v24.3.0"

# Air-gapped / Private registry support
gpu_operator_repository: "https://helm.ngc.nvidia.com/nvidia"
image_pull_secrets: []

# Operator settings
driver_enabled: true
driver_version: "535.129.03"
toolkit_enabled: true
mig_strategy: "single" # none, single, mixed
dcgm_exporter_enabled: true
