---
- name: Create GPU Operator namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ gpu_operator_namespace }}"
    state: present
  when: inventory_hostname == groups['masters'][0]

- name: Add NVIDIA helm repo
  kubernetes.core.helm_repository:
    name: nvidia
    repo_url: "{{ gpu_operator_repository }}"
  when: inventory_hostname == groups['masters'][0]

- name: Deploy GPU Operator
  kubernetes.core.helm:
    name: "{{ gpu_operator_release_name }}"
    chart_ref: nvidia/gpu-operator
    release_namespace: "{{ gpu_operator_namespace }}"
    version: "{{ gpu_operator_chart_version }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    wait: true
  when: inventory_hostname == groups['masters'][0]

- name: Include validation tasks
  include_tasks: validate.yml
  when: inventory_hostname == groups['masters'][0]
