apisix:
  node_listen:
    - 9080
  enable_admin: false
  enable_control: false
  router:
    http: radixtree_host_uri

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

nginx_config:
  http:
    access_log_format: '{"request_id":"$request_id","host":"$host","uri":"$uri","status":"$status","upstream_addr":"$upstream_addr","request_time":"$request_time","upstream_response_time":"$upstream_response_time"}'
